config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :api, defaults:{format: :json} do
    resources :tickets, only: [:create]
  end

  resources :tickets, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/excavator.rb
class Excavator < ApplicationRecord
  belongs_to :ticket
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  has_one :excavator
  accepts_nested_attributes_for :excavator
end

app/controllers/api/api_controller.rb
class Api::ApiController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/api/tickets_controller.rb
class Api::TicketsController < Api::ApiController

  def create
    @ticket = Ticket.new(ticket_params)
    if @ticket.save
      render json: {ticker: @ticket, excavator: @ticket.excavator}
    else
      render json: {error: 'Unable to create ticket'}
    end
  end

  private

  def ticket_params
    date_times = params.fetch(:DateTimes, {}).keys
    excavator = params[:excavator_attributes]
    contact = excavator.fetch(:Contact, {}).keys
    field_contact = excavator.fetch(:FieldContact, {}).keys
    params.permit(:ContactCenter, :RequestNumber,:SequenceNumber, :WellKnownText, :RequestType, :RequestAction, :AdditionalServiceArea, :DigsiteInfo,
                  excavator_attributes: [:CompanyName, :Address, :State, :Zip,
                                         :Type, :CrewOnsite, Contact: contact, FieldContact: field_contact],
                  DateTimes: date_times )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show]

  def index
    @tickets = Ticket.all
  end

  def show
    @cordinates = @ticket.WellKnownText.scan(/[0-9-+.]+ [0-9-+.]+/).map(&:split)
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestTask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tickets/index.html.erb
<table>
  <thead>
  <tr>
    <th>ContactCenter</th>
    <th>RequestNumber</th>
    <th>SequenceNumber</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
    <% @tickets.each do |ticket| %>
    <tr>
      <td><%= ticket.ContactCenter %></td>
      <td><%= ticket.RequestNumber %></td>
      <td><%= ticket.SequenceNumber %></td>
      <td><%= link_to "Show Polygon", ticket_path(ticket) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/tickets/show.html.erb
<div id="dataset" data-cordinates="<%= @cordinates %>"></div>
<canvas id="polygon" class="canvas-width"></canvas>